//
//  PhCity.swift
//  Tourista
//
//  Created by Pinuno Fuentes on 10/6/15.
//  Copyright © 2015 pinunofuentes. All rights reserved.
//
//  Reference: https://en.wikipedia.org/wiki/List_of_cities_in_the_Philippines

import Foundation

enum PhCity {
    case Alaminos
    case Angeles
    case Antipolo
    case Bacolod
    case Bacoor
    case Bago
    case Baguio
    case Bais
    case Balanga
    case Batac
    case Batangas
    case Bayawan
    case Baybay
    case Bayugan
    case Binan
    case Bislig
    case Bogo
    case Borongan
    case Butuan
    case Cabadbaran
    case Cabanatuan
    case Cabuyao
    case Cadiz
    case CagayanDeOro
    case Calamba
    case Calapan
    case Calbayog
    case Caloocan
    case Candon
    case Canlaon
    case Carcar
    case Catbalogan
    case Cauayan
    case Cavite
    case Cebu
    case Cotabato
    case Dagupan
    case Danao
    case Dapitan
    case Dasmarinas
    case Davao
    case Digos
    case Dipolog
    case Dumaguete
    case ElSalvador
    case Escalante
    case Gapan
    case GeneralSantos
    case Gingoog
    case Guihulngan
    case Himamaylan
    case Ilagan
    case Iligan
    case Iloilo
    case Imuis
    case Iriga
    case Isabela
    case Kabankalan
    case Kidapawan
    case Koronadal
    case LaCarlota
    case Lamitan
    case Laoag
    case LapuLapu
    case LasPinas
    case Legazpi
    case Ligao
    case Lipa
    case Lucena
    case Maasin
    case Mabalacat
    case Makati
    case Malabon
    case Malaybay
    case Malolos
    case Mandaluyong
    case Mandaue
    case Manila
    case Marawi
    case Markikina
    case Masbate
    case Mati
    case Meycauayan
    case Munoz
    case Muntinlupa
    case Naga
    case Navotas
    case Olongapo
    case Ormoc
    case Oroquieta
    case Ozamiz
    case Pagadian
    case Palayan
    case Panabo
    case Paranaque
    case Pasay
    case Pasig
    case Passi
    case PuertoPrincesa
    case Quezon
    case Roxas
    case Sagay
    case Samal
    case SanCarlosNegros
    case SanCarlosPangasinan
    case SanFernando
    case SanJose
    case SanJoseDelMonte
    case SanJuan
    case SanPablo
    case SanPedro
    case SantaRosa
    case Santiago
    case Silay
    case Sipalay
    case Sorsogon
    case Surigao
    case Tabaco
    case Tabuk
    case Takloban
    case Tacurong
    case Tagaytay
    case Tagbilaran
    case Taguig
    case Tagum
    case Talisay
    case Tanauan
    case Tandag
    case Tangub
    case Tanjay
    case Tarlac
    case Tayabas
    case Toledo
    case TreceMartires
    case Tuguegarao
    case Urdaneta
    case Valencia
    case Valenzuela
    case Victorias
    case Vigan
    case Zamboanga
}
